FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
             fields: email
             errorPath: email 
             message: fos_user.email.already_used
             groups: [ "WorkshopRegistration" ]
    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "WorkshopRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "WorkshopRegistration" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "WorkshopRegistration"]
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "WorkshopRegistration"]
            - Length:
                min: 2
                minMessage: fos_user.password.blank
                groups: [ "WorkshopRegistration"]
