workshop_catalog:
    resource: "@WorkshopCatalogBundle/Controller/"
    type:     annotation
    prefix:   /

workshop_user:
    resource: "@WorkshopUserBundle/Resources/config/routing.yml"
    prefix: /user

workshop_product:
    resource: "@WorkshopProductBundle/Controller/"
    type:     annotation
    prefix:   /
workshop_acl:
    resource: "@WorkshopAclBundle/Resources/config/routing.yml"
    prefix:   /acl/