<?php

namespace Workshop\Bundle\CatalogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * CatalogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogRepository extends EntityRepository
{
    public function findCatalogName($limit)
    {
        $qb = $this->createQueryBuilder('c');

        return $qb->leftJoin("c.products", "p")
            ->addSelect("Count(p.catalog)")
            ->groupBy('p.catalog')
            ->add('orderBy', 'c.name ASC')
            ->setMaxResults($limit)
            ->getQuery()
            ->getArrayResult();
    }

    public function findCatalogIds($limit)
    {
        $query = $this->getEntityManager()->createQuery(
            '
            SELECT c , p  FROM  WorkshopCatalogBundle:Catalog c JOIN c.products p
'
        );

        return $query->getArrayResult();
    }

    public function findCatalogUnion()
    {
        $sql = "select distinct t.name
                from
                (
                   select name
                   from product4
                   where product4.name like '%2%'
                union
                   select name
                       from catalog p1
                       Where p1.name like '%2%'
                )t";
        $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
        $stmt->execute();

        return $stmt->fetchAll();
    }
}
